exports.ICUFee = [
  {
    value: 'Select',
    name: 'SELECT BED',
    Room_Rent: 0,
    IP_Fee: 0,
    Emergency_Fee: 0,
  },
  {
    value: 'DC',
    name: 'DAY CARE',
    Room_Rent: 4000,
    IP_Fee: 900,
    Emergency_Fee: 1350,
  },
  {
    value: 'EDCEC',
    name: 'EXECUTIVE DAY CARE',
    Room_Rent: 4500,
    IP_Fee: 900,
    Emergency_Fee: 1350,
  },
  {
    value: 'ER1002-A',
    name: 'EMERGENCY BED CHARGES ( PER TWO HOURS)',
    Room_Rent: 800,
    IP_Fee: 'As per Specialty',
    Emergency_Fee: 'As per Specialty',
  },
  {
    value: 'NRICU',
    name: 'NEURO ICU',
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'CTVSIC',
    name: 'CTVS ICU',
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'CCU',
    name: 'CCU',
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'MICU',
    name: 'MICU',
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'SICU',
    name: 'SICU',
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'HDU',
    name: 'HDU',
    Room_Rent: 11000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'DLSUIT',
    name: 'DELIVERY SUITE',
    Room_Rent: 12500,
    IP_Fee: 1500,
    Emergency_Fee: 2250,
  },
  {
    value: 'LDR',
    name: 'LDR SUITE',
    Room_Rent: 12500,
    IP_Fee: 1500,
    Emergency_Fee: 2250,
  },
  {
    value: 'NURS',
    name: 'NURSERY/NICU LEVEL 1',
    Room_Rent: 5500,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'NICU',
    name: 'NICU LEVEL 2',
    Room_Rent: 7000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'NICU3',
    name: 'NICU LEVEL 3',
    Room_Rent: 7500,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'PHDU',
    name: 'PHDU',
    Room_Rent: 7000,
    IP_Fee: 1100,
    Emergency_Fee: 1650,
  },
  {
    value: 'PIC',
    name: 'PICU LEVEL1',
    Room_Rent: 7500,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'PIC2',
    name: 'PICU LEVEL2',
    Room_Rent: 9000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    value: 'CRIBS',
    name: 'CRIBS',
    Room_Rent: 550,
    IP_Fee: 'As per Cat.',
    Emergency_Fee: 'As per Cat.',
  },
];
